version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    expose:
      - "3306"
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=ok
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./skyshi-app
    restart: unless-stopped
    env_file: ./.env
    command: bash -c 'while !</dev/tcp/mysqldb/3306; do sleep 1; done; npm start'
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST:mysqldb
      - DB_USER:$MYSQLDB_USER
      - DB_PASSWORD:$MYSQLDB_ROOT_PASSWORD
      - DB_NAME:$MYSQLDB_DATABASE
      - DB_PORT:$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
  