version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: skyshi_backend_test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
    
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3030:3030
    expose:
      - 3030
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 
      DB_NAME: skyshi_backend_test
      SERVICE_NAME: nodeappservice
      PORT: 3030
    depends_on:
      - mysqldb
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge