version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    # container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    # volumes:
    #   - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql:z
    #   - ./database:/var/lib/mysql:z
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - ./.env
    networks:
      - internalnet
  nodeapp:
    restart: unless-stopped
    # container_name: nodeappcontainer
    build:
      context: .
      dockerfile: Dockerfile
    # image: nodeapp
    volumes:
      - ./app:/code:z
      - /code/node_modules
    ports:
      - 3030:3030
    env_file:
      - ./.env
    depends_on:
      - mysqldb
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
